### 实践一：出事了，请尽量保留事故现场

保留事故现场，主要涉及：异常发生时的上下文的信息是否记录了、异常堆栈是否被忽略了、异常是否没抓到。

####   有助排错的上下文信息是否记录了?
1，方法抛出异常时，最好提供一些上下文信息，例如：

 ``` java
      public  Employee findByUserCode(int userCode){
      if(userCode < 0){
         //不推荐：
          throw new IllegalArgumentException(“工号非法”)
        //推荐，尽可能提供必要的信息方便排查
        throw new IllegalArgumentException(“工号非法,userCode=”+userCode)
      }
}
```

2，同理，最终调用方捕捉异常时，应该记录必要的排错信息：
``` java
public void sendMessage(int userCode,long resblockId){
 try{ 
     Resblock r=findMyResblock(userCode,resblockId);
 }catch(BizException e){
        //不推荐
        //以前见过有同学使用log4j这样写，其实很多日志框架，单个参数的方法一般都只输出message的，这样写会丢掉堆栈信息；
        logger.error(e)
        
       // 不推荐，大多数情况下只能干瞪眼，无法定位问题。
       logger.error(e.getMessage());
       
       //推荐
      logger.error(“查找我的楼盘出错，userCode=”+userCode+“,resblockId=”+resblockId,e);
}
}
```

#### 异常堆栈是否被忽略了？
        
1，方法封装异常重新抛出时，应该保留原始堆栈信息。
``` java
 public void sendMessage(int userCode,long resblockId){
 try{ 
     Resblock r=restTemplate.exchange(userCode,resblockId);
 }catch(RestException e){
    // 最终调用方e.printStachTrace()获取不到RestException的堆栈，不利于定位问题。
    //不推荐：
     throw new BizExcetpion(e.getMessage());
    //推荐
    throw new BizException(e);
   //推荐：或者提供更完善的message
   throw new BizExcetpion(“发送消息异常：userCode=”+userCode+”,resblockId=“+resblockId,e);
}
}
```

2，小心使用Try-Finally语句关闭资源，推荐正确使用Try-with-Resource。

比如以下代码：
 ``` java 
    public String readAllLines(File file){
       try{
        throw new ExceptionA();
        }finally{
          //关闭流的时候也可能抛出错误
         throw new ExceptionB();
        }
    }
```

以上代码如果try代码块和流关闭同时抛出异常，跟业务有关的ExceptionA将被忽略，调用方只能获取和业务无关的ExceptionB，这对排错是不利的。

这可以使用JDK7的try-with-resource语法糖避免：
``` java
public String readAllLines(File file){
       try(打开流){
        throw new ExceptionA();
        }
    }
```
上述代码，如果try代码块和流关闭同时抛出异常，调用方将获取和业务相关的ExcetpionA，如果想获取ExceptionB，可以调用ExcetpionA.getSuppressed();

使用try-with-resource时，有一些细节需要留意：

``` java
public static String readAllLines(String filePath) throws FileNotFoundException, IOException{
    //bufferSize小于0，构造bufferedReader会报错。
    int bufferSize = -1;
    try (BufferedReader br = new BufferedReader(new FileReader(filePath), bufferSize)){
        return read(br);
    } 
}

```
以上代码，如果构造BufferedReader出错，JVM不会正确地关闭文件流FileReader，正确写法应该是拆成两个：
``` java
public static String readAllLines(String filePath) throws FileNotFoundException, IOException{
    int bufferSize=4096;
    try (FileReader reader=new FileReader(filePath);
    BufferedReader br = new BufferedReader(reader, sz)){
        return read(br);
    } 
}

```
JVM只会调用在try代码块里初始化了的变量的close方法。

3，小心JVM运行时优化，如果异常频繁抛出，异常堆栈信息将被忽略

有些小伙伴即使记录日志的方法正确，比如： logger.error(“message”,e)，有时候也看不到堆栈信息，导致无法及时定位问题。

JRE5以后，JVM以-server模式启动，JIT运行时会对一些频繁抛出的异常重新编译，出于性能考虑，会忽视堆栈信息，当然，早期的日志记录里是可以看到完整的堆栈信息的，禁用这项优化可以在启动参数里添加：-XX:-OmitStackTraceInFastThrow。

不过话说回来，如果这么频繁抛出异常，不如早点bug fixed.


#### 异步时异常没抓到，遛走了 ?

1， 如果是我们自己管理线程，记得设置线程的UncaughtExceptionHandler：
```java
 //启动一个线程，如果出现异常则打印日志。
 public static void runThread(final Runnable runCall, String threadName) {
		Thread thread = new Thread(runCall, threadName);

		thread.setDaemon(false);
		thread.setUncaughtExceptionHandler(new UncaughtExceptionHandler() {
			@Override
			public void uncaughtException(Thread t, Throwable e) {
				logger.error("thread exception:threadName=" + t.getName(), e);
			}
		});
		thread.start();
	}
```

2，如果使用线程池，比如Spring的线程池，也请记得设置线程的异常处理器：
``` java
@Configuration
public class AsyncCustomizeConfig extends AsyncConfigurerSupport {
	@Override
	public Executor getAsyncExecutor() {
		//…..
	}
	/**
	 * 发生异常时只是记录下日志
	 */
	@Override
	public AsyncUncaughtExceptionHandler getAsyncUncaughtExceptionHandler() {
		return new SimpleAsyncUncaughtExceptionHandler();
	}
```